// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1) {
  return window['go']['main']['App']['CheckFileExists'](arg1);
}

export function FetchSimulatorOutput() {
  return window['go']['main']['App']['FetchSimulatorOutput']();
}

export function IsSimulatorRunning() {
  return window['go']['main']['App']['IsSimulatorRunning']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function StartSimulator(arg1) {
  return window['go']['main']['App']['StartSimulator'](arg1);
}

export function StopSimulator() {
  return window['go']['main']['App']['StopSimulator']();
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
