// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1) {
  return window['go']['main']['App']['CheckFileExists'](arg1);
}

export function DaemonAction(arg1, arg2) {
  return window['go']['main']['App']['DaemonAction'](arg1, arg2);
}

export function DaemonGetInfo() {
  return window['go']['main']['App']['DaemonGetInfo']();
}

export function FetchSimulatorOutput() {
  return window['go']['main']['App']['FetchSimulatorOutput']();
}

export function InstallSmartContract(arg1, arg2) {
  return window['go']['main']['App']['InstallSmartContract'](arg1, arg2);
}

export function IsSimulatorRunning() {
  return window['go']['main']['App']['IsSimulatorRunning']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function StartSimulator(arg1) {
  return window['go']['main']['App']['StartSimulator'](arg1);
}

export function StopSimulator() {
  return window['go']['main']['App']['StopSimulator']();
}

export function WalletAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['WalletAction'](arg1, arg2, arg3);
}

export function WalletInfo(arg1) {
  return window['go']['main']['App']['WalletInfo'](arg1);
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
