// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1:string):Promise<boolean>;

export function DaemonAction(arg1:string,arg2:any):Promise<{[key: string]: any}>;

export function DaemonGetInfo():Promise<{[key: string]: any}>;

export function FetchSimulatorOutput():Promise<Array<string>>;

export function InstallSmartContract(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function IsSimulatorRunning():Promise<boolean>;

export function OpenFile():Promise<string>;

export function ReadConfig():Promise<Array<string>>;

export function StartSimulator(arg1:string):Promise<void>;

export function StopSimulator():Promise<void>;

export function WalletAction(arg1:string,arg2:string,arg3:any):Promise<{[key: string]: any}>;

export function WalletInfo(arg1:string):Promise<{[key: string]: any}>;

export function WriteConfig(arg1:string):Promise<void>;
