// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1:string):Promise<boolean>;

export function FetchSimulatorOutput():Promise<Array<string>>;

export function IsSimulatorRunning():Promise<boolean>;

export function OpenFile():Promise<string>;

export function ReadConfig():Promise<Array<string>>;

export function StartSimulator(arg1:string):Promise<void>;

export function StopSimulator():Promise<void>;

export function WriteConfig(arg1:string):Promise<void>;
